/**
 * Generates idempotent SQL to load the drill corpus into D1.
 *
 * Run via `bun run db:seed`, which pipes the output through
 * `wrangler d1 execute --local`. Keeping content out of migrations means editing a drill
 * is a one-line diff here plus a re-run, rather than another append-only migration.
 *
 * Uses INSERT OR REPLACE so re-running is safe and picks up edits. Drill ids are stable
 * slugs, so attempts keep pointing at the right drill across re-seeds.
 */
import { DRILLS } from '../content/drills';

/** Escapes a string for safe inclusion in a single-quoted SQL literal. */
function sql(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const statements = DRILLS.map(
  (d) =>
    `INSERT OR REPLACE INTO drills ` +
    `(id, sentence, target_ipa, feature, difficulty, coaching_note, has_r_context, sort_order) VALUES (` +
    [
      sql(d.id),
      sql(d.sentence),
      sql(d.targetIpa),
      sql(d.feature),
      d.difficulty,
      sql(d.coachingNote),
      d.hasRContext ? 1 : 0,
      d.sortOrder,
    ].join(', ') +
    `);`,
);

const ids = DRILLS.map((d) => sql(d.id)).join(', ');

process.stdout.write(
  [
    `-- Generated by scripts/seed.ts — do not edit. Source: content/drills.ts`,
    ...statements,
    // Remove drills that have been deleted from the corpus, without touching attempts
    // that reference drills still present.
    `DELETE FROM drills WHERE id NOT IN (${ids});`,
    '',
  ].join('\n'),
);
