/**
 * Generates idempotent SQL to load the drill corpus into D1.
 *
 * Run via `bun run db:seed`, which pipes the output through
 * `wrangler d1 execute --local`. Keeping content out of migrations means editing a drill
 * is a one-line diff here plus a re-run, rather than another append-only migration.
 *
 * Uses INSERT OR REPLACE so re-running is safe and picks up edits. Drill ids are stable
 * slugs, so attempts keep pointing at the right drill across re-seeds.
 */
import { DRILLS } from '../content/drills';

/** Escapes a string for safe inclusion in a single-quoted SQL literal. */
function sql(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const statements = DRILLS.map(
  (d) =>
    `INSERT OR REPLACE INTO drills ` +
    `(id, sentence, target_ipa, feature, difficulty, coaching_note, has_r_context, sort_order) VALUES (` +
    [
      sql(d.id),
      sql(d.sentence),
      sql(d.targetIpa),
      sql(d.feature),
      d.difficulty,
      sql(d.coachingNote),
      d.hasRContext ? 1 : 0,
      d.sortOrder,
    ].join(', ') +
    `);`,
);

const ids = DRILLS.map((d) => sql(d.id)).join(', ');

process.stdout.write(
  [
    `-- Generated by scripts/seed.ts — do not edit. Source: content/drills.ts`,
    ...statements,
    // Remove drills dropped from the corpus — but only those nobody has practised. Foreign
    // keys are enforced, so deleting a drill with attempts would fail the whole seed; and
    // the attempts are the learner's history, which retiring a drill should not erase.
    // A retired drill with history therefore stays in the table, and is still listed by
    // GET /api/drills. Hiding it needs a `retired` column — a schema change, not made here.
    `DELETE FROM drills WHERE id NOT IN (${ids})` +
      ` AND id NOT IN (SELECT DISTINCT drill_id FROM attempts);`,
    '',
  ].join('\n'),
);
